[package]
name = "Ag2O"
version = "0.1.0"
edition = "2024"

[dependencies]
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
objc2-metal = "0.3.2"
objc2-metal-kit = "0.3.2"
objc2-quartz-core = "0.3.2"
raw-window-handle = "0.6.2"
winit = "0.30.12"
